services:
  api:
    image: simple-api
    environment:
      DB_URL: mongodb://mongo:27017
    container_name: my-api
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    restart: unless-stopped

  mongo:
    image: mongo:4.4.6
    container_name: my-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
